#!/data/data/com.termux/files/usr/bin/bash

# Dependencies - webtorrent, binutils, git, nodejs, fzf

clear

mkdir -p "$HOME"/.cache/notflix

menu="fzf"
baseurl="https://1337x.to"
cachedir="$HOME/.cache/notflix"

# Display number of pages for result should be set from 2+
pages="3"

if [ -z "$1" ]; then
  clear
  url="$baseurl/home/"
else
  query="$1"
  url="$baseurl/search/$query/1/"
fi

query=${query// /+}

curl -s "$url" > "$cachedir"/tmp.html

# Remove other torrents from homepage
sed -i '/Popular Music Torrents/,$d' "$cachedir"/tmp.html

# Append additional result pages if arg is passed
if [ "$1" ]; then
for ((i=2;i<="$pages";i++)) do curl -s "$baseurl/search/$query/$i/" >> "$cachedir"/tmp.html; done
fi

# Get Titles
grep -o '<a href="/torrent/.*</a>' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g' > "$cachedir"/titles.bw

result_count=$(wc -l "$cachedir"/titles.bw | awk '{print $1}')
if [ "$result_count" -lt 1 ]; then
  echo "No Result found. Try again"
  exit 0
fi

# Seeders and Leechers
grep -o '<td class="coll-2 seeds.*</td>\|<td class="coll-3 leeches.*</td>' "$cachedir"/tmp.html |
  sed 's/<[^>]*>//g' | sed 'N;s/\n/ /' > "$cachedir"/seedleech.bw

# Size
grep -o '<td class="coll-4 size.*</td>' "$cachedir"/tmp.html |
  sed 's/<span class="seeds">.*<\/span>//g' |
  sed -e 's/<[^>]*>//g' > "$cachedir"/size.bw

# Links
grep -E '/torrent/' "$cachedir"/tmp.html |
  sed -E 's#.*(/torrent/.*)/">.*/#\1#' |
  sed 's/td>//g' > "$cachedir"/links.bw

# Clearning up some data to display
sed 's/\./ /g; s/\-/ /g' "$cachedir"/titles.bw |
  sed 's/[^A-Za-z0-9 ]//g' | tr -s " " > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/titles.bw

awk '{print NR " - ["$0"]"}' "$cachedir"/size.bw > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/size.bw

awk '{print "[S:"$1 " L:"$2"]" }' "$cachedir"/seedleech.bw > "$cachedir"/tmp && mv "$cachedir"/tmp "$cachedir"/seedleech.bw

# Getting the line number
LINE="$(paste -d\  "$cachedir"/{size.bw,seedleech.bw,titles.bw} |
  $menu |
  cut -d\- -f1 |
  awk '{$1=$1; print}')"
#echo "Select your stream"
#read LINE

if [ -z "$LINE" ]; then
  echo "No Result selected. Exiting..."
  exit 0
fi

clear

echo "Searching Magnet seeds"
url=$(head -n $LINE "$cachedir"/links.bw | tail -n +$LINE)
fullURL="${baseurl}${url}/"

# Requesting page for magnet link
curl -s "$fullURL" > "$cachedir"/tmp.html
magnet=$(grep -o "magnet.*" "$cachedir"/tmp.html | cut -d'"' -f1 | head -n 1)

# Clear webtorrent cache at exit
trap "rm -rf $TMPDIR/webtorrent/*" EXIT

webtorrent "$magnet" --mpv --no-quit
